name: Deploy and run on Azure VM

on:
  push:
    branches: [ stable ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2
  
      - name: Start lavalink server and bot
        uses: fifsky/ssh-action@v0.0.6
        with:
            command: |
              cd ~/dev/Obsidian/lavalink_server
              java -jar Lavalink.jar

              cd ..
              dart pub get
              dart run

            host: ${{ secrets.HOST }}
            user: dhzdhd
            key: ${{ secrets.PRIVATE_KEY }}
            args: "-tt"

      # - name: Start bot      
      #   uses: fifsky/ssh-action@v0.0.6 
      #   with:
      #       command: |
      #         cd ~/dev/Obsidian
      #         dart pub get
      #         dart run

      #       host: ${{ secrets.HOST }}
      #       user: dhzdhd
      #       key: ${{ secrets.PRIVATE_KEY }}
      #       args: "-tt"